
export const examData = {
  exam: {
    title: "Sample Exam",
    description: "This is a sample exam with different types of questions.",
    questions: [
      {
        id: 1,
        type: "multiple_choice",
        question: "What is the capital of France?",
        options: ["Paris", "London", "Berlin", "Madrid"],
        answer: "Paris",
      },
      {
        id: 2,
        type: "matrix_multiple_choice",
        question: "Match the countries with their capitals.",
        options: [
          {
            question: "Italy",
            choices: ["Rome", "Paris"],
            answer: "Rome",
          },
          {
            question: "Japan",
            choices: ["Tokyo", "London"],
            answer: "Tokyo",
          },
        ],
      },
      {
        id: 3,
        type: "multiple_response_select",
        question: "Select all the programming languages.",
        options: [
          "Java",
          "Python",
          "C++",
          "JavaScript",
          "Ruby",
          "Swift",
          "HTML/CSS",
        ],
        answers: ["Java", "Python", "JavaScript"],
      },
      {
        id: 4,
        type: "multiple_response_select_apply",
        question: "Select all the fruits and apply them.",
        options: [
          "Apple",
          "Carrot",
          "Banana",
          "Potato",
          "Tomato",
          "Mango",
          "Orange",
        ],
        answers: ["Apple", "Banana"],
      },
      {
        id: 5,
        type: "multiple_choice",
        question: "What is the largest planet in our solar system?",
        options: ["Jupiter", "Saturn", "Neptune", "Mars"],
        answer: "Jupiter",
      },
      {
        id: 6,
        type: "multiple_choice",
        question: "Who painted the Mona Lisa?",
        options: [
          "Leonardo da Vinci",
          "Vincent van Gogh",
          "Pablo Picasso",
          "Michelangelo",
        ],
        answer: "Leonardo da Vinci",
      },
      {
        id: 7,
        type: "matrix_multiple_choice",
        question: "Match the animals with their habitats.",
        options: [
          {
            question: "Lion",
            choices: ["Savannah", "Ocean"],
            answer: "Savannah",
          },
          {
            question: "Whale",
            choices: ["Savannah", "Ocean"],
            answer: "Ocean",
          },
        ],
      },
      {
        id: 8,
        type: "multiple_response_select",
        question: "Select all the colors of the rainbow.",
        options: [
          "Red",
          "Green",
          "Blue",
          "Yellow",
          "Purple",
          "Orange",
          "Black",
        ],
        answers: ["Red", "Green", "Blue", "Yellow", "Purple", "Orange"],
      },

      {
        id: 10,
        type: "multiple_choice",
        question: "Which planet is known as the Red Planet?",
        options: ["Mars", "Earth", "Venus", "Mercury"],
        answer: "Mars",
      },
      {
        id: 11,
        type: "multiple_choice",
        question: "Who wrote 'To Kill a Mockingbird'?",
        options: [
          "Harper Lee",
          "Mark Twain",
          "J.K. Rowling",
          "Charles Dickens",
        ],
        answer: "Harper Lee",
      },
      {
        id: 12,
        type: "matrix_multiple_choice",
        question: "Match the composers with their famous works.",
        options: [
          {
            question: "Beethoven",
            choices: ["Symphony No. 5", "The Four Seasons"],
            answer: "Symphony No. 5",
          },
          {
            question: "Vivaldi",
            choices: ["Symphony No. 5", "The Four Seasons"],
            answer: "The Four Seasons",
          },
        ],
      },
      {
        id: 13,
        type: "multiple_response_select",
        question: "Select all the countries in Europe.",
        options: [
          "France",
          "Germany",
          "Italy",
          "Japan",
          "Spain",
          "Sweden",
          "Switzerland",
        ],
        answers: [
          "France",
          "Germany",
          "Italy",
          "Spain",
          "Sweden",
          "Switzerland",
        ],
      },
      {
        id: 14,
        type: "multiple_response_select_apply",
        question: "Select all the shapes and apply them.",
        options: [
          "Circle",
          "Triangle",
          "Square",
          "Rectangle",
          "Pentagon",
          "Hexagon",
        ],
        answers: ["Circle", "Square", "Rectangle"],
      },
      {
        id: 15,
        type: "multiple_choice",
        question: "Who discovered penicillin?",
        options: [
          "Alexander Fleming",
          "Marie Curie",
          "Louis Pasteur",
          "Albert Einstein",
        ],
        answer: "Alexander Fleming",
      },
    ],
  },
};
