export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';


export const SEARCH_OPEN = 'SEARCH_OPEN';
export const SEARCH_CLOSE = 'SEARCH_CLOSE';

export const FILTERPAGE_OPEN = 'FILTERPAGE_OPEN';
export const FILTERPAGE_CLOSE = 'FILTERPAGE_CLOSE';

export const VERIFYPOPUP_OPEN = 'VERIFYPOPUP_OPEN';
export const VERIFYPOPUP_CLOSE = 'VERIFYPOPUP_CLOSE';

export const REVIEWPOPUP_OPEN = 'REVIEWPOPUP_OPEN';
export const REVIEWPOPUP_CLOSE = 'REVIEWPOPUP_CLOSE';



